DROP FUNCTION @extschema@.add_job(REGPROC, INTERVAL, JSONB, TIMESTAMPTZ, BOOL, REGPROC);

CREATE FUNCTION @extschema@.add_job(REGPROC, INTERVAL, JSONB, TIMESTAMPTZ, BOOL)
RETURNS INTEGER AS '@MODULE_PATHNAME@', 'ts_job_add' LANGUAGE C VOLATILE;

