name: Check CHANGELOG.md update
on:
  pull_request:
jobs:
  # Count the number of commits in a pull request. This can be
  # disabled by adding a trailer line of the following form to the
  # pull request message:
  #
  #    Disable-Check: changelog-update
  #
  # The check is case-insensitive and ignores other contents on the
  # line as well, so it is possible to add several different checks if
  # that is necessary.
  #
  # It is assumed that the trailer is following RFC2822 conventions,
  # but this is currently not enforced.
  check_changelog_update:
    name: Check for CHANGELOG.md update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check CHANGELOG.md updated by pull request
        shell: bash --norc --noprofile {0}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }}
        run: |
          diff=$(git diff --name-status origin/main | grep "CHANGELOG.md")
          # echo "diff is ${diff}"
          # cat << "EOF" | egrep -qsi '^disable-check:.*\<commit-count\>'
          # ${{ github.event.pull_request.body }}
          # EOF
          # if [[ $? -ne 0 ]]; then
            # changelog=$(gh pr view $PULL_REQUEST_NUMBER --json files --jq '.files.[].path' | select(contains("CHANGELOG.md")))
            # echo "changelog is ${changelog}"
            if [[ $diff == '' ]]; then
              echo "CHANGELOG.md not updated by pull request"
              echo
              echo "To disable changelog update check, add this trailer to pull request message:"
              echo
              echo "Disable-check: changelog-update"
              echo
              echo "Trailers follow RFC2822 conventions, so no whitespace"
              echo "before field name and the check is case-insensitive for"
              echo "both the field name and the field body."
              exit 1
            fi
          # fi

# - name: Checkout source
      #   uses: actions/checkout@v2
      #   with:
      #     ref: ${{ github.event.pull_request.head.sha }}
      #     fetch-depth: 0
      # - name: Check CHANGELOG.md updated by pull request
      #   shell: bash --norc --noprofile {0}
      #   run: |
      #     cat << "EOF" | egrep -qsi '^disable-check:.*\<changelog-update\>'
      #     ${{ github.event.pull_request.body }}
      #     EOF
      #     if [[ $? -ne 0 ]]; then
      #       updated=`git diff --name-status main | grep CHANGELOG.md`
      #       if [[ $updated == '' ]]; then
      #         echo "CHANGELOG not updated by pull request"
      #         echo
      #         echo "To disable changelog update check, add this trailer to pull request message:"
      #         echo
      #         echo "Disable-check: changelog-update"
      #         echo
      #         echo "Trailers follow RFC2822 conventions, so no whitespace"
      #         echo "before field name and the check is case-insensitive for"
      #         echo "both the field name and the field body."
      #         exit 1
      #       fi
      #     fi
